### ISSUE TITLE
Support for custom directives arguments

### ISSUE THREAD

**Issue by longnh301** [luwanquan/babel-preset-vca-jsx#1]
Add support for custom directive syntax similar to `vCustomDirective[directive.args]={directive.value}`

**Comment by luwanquan** [comment]
This does not match the [JSX](https://github.com/facebook/jsx) specification and is therefore not intended to be implemented.

If you need or are interested in it, you can implement it in a new project.
Otherwise, it is recommended that you use the expansion operator to pass the parameters.
like e.g.:

``` javascript
const directives = [
  { name: 'my-dir', value: 123, modifiers: { abc: true } }
]
return <div {...{ directives }}/>
```

**Comment by longnh301** [comment]
Thank you, that's how I'm implementing it at the moment.
